name: AutoRuleStatsAndConversion
on:
  push:
    branches:
      - main
    paths:
      - 'rules/*.list'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up time zone
        run: sudo timedatectl set-timezone Asia/Shanghai
      
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get last commit files
        id: last_commit
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Get changed files
        id: file_list
        run: |
          COMMIT=${{ env.sha }}
          URL="https://api.github.com/repos/${{ github.repository }}/compare/${COMMIT}^...${COMMIT}"
          FILES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $URL | jq -r '.files[] | select(.filename | test("^rules/.*\\.list$")) | .filename')
          
          # 更新文件内容
          for file in $FILES; do
            # 获取当前时间
            current_date=$(TZ=Asia/Shanghai date '+%Y年%m月%d日%H:%M:%S')

            # 统计非空行和非注释行的数量
            count=$(grep -v -e '^$' -e '^#' -e '^!' $file | wc -l)
            count_with_unit="${count}条"

            # 修改数量和日期
            sed -i "s/^# 更新: .*/# 更新: $current_date/" $file
            sed -i "s/^# 数量: .*/# 数量: $count_with_unit/" $file
            # 修正字符
            sed -i 's/＞/>/g' $file
            # 修改规则正序
            temp_file=$(mktemp)
            domain_list=""
            while IFS= read -r line || [[ -n $line ]]; do
              if [[ ! $line =~ ^[!#[:space:]]*$ && $line =~ ^(IP|DOMAIN).* ]]; then
                domain_list="$domain_list"$'\n'"$line"
              else
                if [[ $domain_list ]]; then
                  echo "$domain_list" | sort | sed '/^$/d' >> "$temp_file"
                  domain_list=""
                fi
                echo "$line" >> "$temp_file"
              fi
            done < "$file"
            if [[ $domain_list ]]; then
              echo "$domain_list" | sort | sed '/^$/d' >> "$temp_file"
            fi
            mv "$temp_file" "$file"

           # 转换classical规则
           mkdir -p rules/classical
           cp "$file" "rules/classical/$(basename $file .list).yaml"
           sed -i '1s/^/payload:\n/' "rules/classical/$(basename $file .list).yaml"
           sed -i '1!{/^DOMAIN\|^IP/!d; s/^/  - /}' "rules/classical/$(basename $file .list).yaml"
          done

      - name: Update README
        run: |
          # 获取当前时间和规则总数
          new_date=$(TZ='Asia/Shanghai' date +'%Y年%m月%d日%H:%M:%S')
          count_1=$(grep -v -e '^$' -e '^#' -e '^!' rules/*.list | grep -v 'Adblack.list' | wc -l)

          # 更新README.md内容
          sed -i "s/最近更新: .*/最近更新: $new_date/" README.md
          sed -i "s/规则数量: .*/规则数量: $count_1条/" README.md
          
      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update rule statistics and conversion"
          git push
